#!/bin/bash

curdir=`pwd`
basedir=`dirname $curdir`
buildroot=$basedir/temp
prefix=/opt/monitor/op5/livestatus

PATH_DEF=$PATH
PATH=/usr/sbin:/usr/bin:/opt/csw/bin:/usr/local/bin:/usr/ccs/bin/

cd livestatus
	aclocal && autoheader && automake -a
	autoconf || :
	./configure
	make
cd ../

mkdir -p $buildroot/$prefix
mkdir -p $buildroot/usr/bin
cp -f livestatus/src/livestatus.o $buildroot$prefix
cp -f livestatus/src/unixcat $buildroot/usr/bin

PATH=$PATH_DEF
