#!/bin/sh

nagios_cfg=/opt/monitor/etc/nagios.cfg
prefix=/opt/monitor/op5/livestatus

/usr/xpg4/bin/grep -q 'broker_module.*livestatus.o' $nagios_cfg
if [ $? -eq 1 ]; then
        /opt/csw/bin/gsed -i "s#^log_file.*#broker_module=$prefix/livestatus.o /opt/monitor/var/rw/live\\n\\n&#" \
               $nagios_cfg
fi

svcadm restart monitor
