name: citest

on:
  push:
  pull_request:
  release:

jobs:
  citest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      #- name: Setup tmate session, see https://github.com/marketplace/actions/debugging-with-tmate
      #  uses: mxschmitt/action-tmate@v3
      - name: prepare machine
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https
          sudo sh -c "echo 'deb [signed-by=/etc/apt/trusted.gpg.d/naemon.asc] http://download.opensuse.org/repositories/home:/naemon:/daily/xUbuntu_$(lsb_release -rs)/ ./' >> /etc/apt/sources.list"
          sudo curl -s -o /etc/apt/trusted.gpg.d/naemon.asc "https://build.opensuse.org/projects/home:naemon/signing_keys/download?kind=gpg"
          sudo apt-get update
          sudo apt-get install autoconf
          sudo apt-get install build-essential
          sudo apt-get install libcppunit-dev
          sudo apt-get install libglib2.0-dev
          sudo apt-get install libtool
          sudo apt-get install naemon-dev
          sudo apt-get install naemon-core
          sudo apt-get install cucumber

      - name: run build
        run: |
          autoreconf -i
          ./configure
          make

      - name: run make check
        run: make check

      - name: run cucumber tests
        run: make tests-cucumber

